apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-frontend
  labels:
    app: workflow-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-frontend
  template:
    metadata:
      labels:
        app: workflow-frontend
    spec:
      containers:
        - name: workflow-frontend
          image: reijiokito/workflow-frontend:latest
          ports:
            - containerPort: 80
