apiVersion: v1
kind: Service
metadata:
  name: workflow-frontend
spec:
  type: NodePort
  selector:
    app: workflow-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can choose a different port in range 30000–32767
